chore(tests): rework justfile

diff --git a/tests/justfile b/tests/justfile
--- a/tests/justfile
+++ b/tests/justfile
@@ -46,7 +46,19 @@ build-kona:
   #!/bin/bash
   cd {{SOURCE}}/.. && cargo build --bin kona-node
 
-acceptance-tests CL_TYPE="kona" EL_TYPE="op-reth" GATE="jovian": build-kona build-reth (acceptance-tests-run CL_TYPE EL_TYPE GATE)
+acceptance-tests CL_TYPE="kona" EL_TYPE="op-reth" GATE="jovian": 
+  #!/bin/bash
+  if [ "{{CL_TYPE}}" = "kona" ] ; then
+    echo "Building kona-node..."
+    just build-kona
+  fi
+
+  if [ "{{EL_TYPE}}" = "op-reth" ] ; then
+    echo "Building op-reth..."
+    just build-reth
+  fi
+
+  just acceptance-tests-run {{CL_TYPE}} {{EL_TYPE}} {{GATE}}
 
 # Run acceptance tests for the rust stack. By default runs the acceptance tests for kona-node with op-reth.
 # Uses the jovian gate by default.
@@ -55,16 +67,14 @@ acceptance-tests-run CL_TYPE="kona" EL_TYPE="op-reth" GATE="jovian":
   if [ "{{CL_TYPE}}" = "kona" ] ; then
     echo "Running acceptance tests for kona-node"
     export KONA_NODE_EXEC_PATH="{{SOURCE}}/../target/debug/kona-node"
-  else
-    echo "Running acceptance tests for op-node"
   fi
 
   if [ "{{EL_TYPE}}" = "op-reth" ] ; then
     echo "Running acceptance tests for op-reth"
     export OP_RETH_EXEC_PATH="{{SOURCE}}/reth/target/debug/op-reth"
-  else
-    echo "Running acceptance tests for op-geth"
   fi
+
+  echo "Running acceptance tests for {{CL_TYPE}} with {{EL_TYPE}} on gate {{GATE}}..."
 
   export DEVSTACK_L2CL_KIND="{{CL_TYPE}}"
   export DEVSTACK_L2EL_KIND="{{EL_TYPE}}"
@@ -73,23 +83,48 @@ acceptance-tests-run CL_TYPE="kona" EL_TYPE="op-reth" GATE="jovian":
 
 # Run the e2e tests for the sysgo orchestrator.
 # Builds the kona-node and op-reth binaries, unzips the contract artifacts, and runs the tests.
-test-e2e-sysgo BINARY GO_PKG_NAME="" DEVNET="simple-kona" FILTER="" : build-kona build-reth unzip-contract-artifacts (test-e2e-sysgo-run BINARY GO_PKG_NAME DEVNET FILTER)
+test-e2e-sysgo BINARY="node" GO_PKG_NAME="node/common" DEVNET="simple-kona" FILTER="" :
+    #!/bin/bash
+    if [ "{{BINARY}}" = "node" ]; then
+      echo "Building kona-node..."
+      just build-kona
+      echo "Building op-reth..."
+      just build-reth
+    elif [ "{{BINARY}}" = "supervisor" ]; then
+      echo "Building supervisor..."
+      cd {{SOURCE}}/.. && just build-supervisor
+    fi
+
+    echo "Unzipping contract artifacts..."
+    just unzip-contract-artifacts
+
+    just test-e2e-sysgo-run {{BINARY}} {{GO_PKG_NAME}} {{DEVNET}} {{FILTER}}
 
 # Run the e2e tests for the sysgo orchestrator. Don't build the binaries or unzip the contract artifacts.
-test-e2e-sysgo-run BINARY GO_PKG_NAME="" DEVNET="simple-kona" FILTER="" :
+test-e2e-sysgo-run BINARY="node" GO_PKG_NAME="node/common" DEVNET="simple-kona" FILTER="" :
     #!/bin/bash
-    if [ -z "{{GO_PKG_NAME}}" ]; then
-        export GO_PKG_NAME="..."
+    echo "Running e2e tests for the sysgo orchestrator for binary {{BINARY}} with package name {{GO_PKG_NAME}} on devnet {{DEVNET}}..."
+
+    export OP_DEPLOYER_ARTIFACTS="{{SOURCE}}/artifacts/src/forge-artifacts"
+    export DISABLE_OP_E2E_LEGACY=true
+    export DEVSTACK_ORCHESTRATOR=sysgo
+    export GO_PKG_NAME="{{GO_PKG_NAME}}"
+
+    if [ "{{BINARY}}" = "node" ]; then
+        export KONA_NODE_EXEC_PATH="{{SOURCE}}/../target/debug/kona-node"
+        export OP_RETH_EXEC_PATH="{{SOURCE}}/reth/target/debug/op-reth"
+    elif [ "{{BINARY}}" = "supervisor" ]; then
+        export DEVSTACK_SUPERVISOR_KIND=kona
+        export KONA_SUPERVISOR_EXEC_PATH="{{SOURCE}}/../target/release/kona-supervisor"
     else
-        export GO_PKG_NAME="{{GO_PKG_NAME}}"
+        echo "Invalid BINARY specified. Must be either 'node' or 'supervisor'."
+        exit 1
     fi
 
     if ! [ -z "{{FILTER}}" ]; then
         export FILTER="-run {{FILTER}}"
+        echo "Running tests with filter {{FILTER}}..."
     fi
-
-    export OP_DEPLOYER_ARTIFACTS="{{SOURCE}}/artifacts/src/forge-artifacts"
-    export DISABLE_OP_E2E_LEGACY=true
 
     if [ "{{DEVNET}}" = "simple-kona" ]; then
         export KONA_SEQUENCER_WITH_RETH=0
@@ -131,20 +166,6 @@ test-e2e-sysgo-run BINARY GO_PKG_NAME="" DEVNET="simple-kona" FILTER="" :
         export OP_VALIDATOR_WITH_RETH=0
         export OP_SEQUENCER_WITH_GETH=0
         export OP_VALIDATOR_WITH_GETH=0
-    fi
-
-    if [ "{{BINARY}}" = "node" ]; then
-        export KONA_NODE_EXEC_PATH="{{SOURCE}}/../target/debug/kona-node"
-        export OP_RETH_EXEC_PATH="{{SOURCE}}/reth/target/debug/op-reth"
-        export DEVSTACK_ORCHESTRATOR=sysgo
-    elif [ "{{BINARY}}" = "supervisor" ]; then
-        export DEVSTACK_SUPERVISOR_KIND=kona
-        export KONA_SUPERVISOR_EXEC_PATH="{{SOURCE}}/../target/release/kona-supervisor"
-        export DEVSTACK_ORCHESTRATOR=sysgo
-        cd {{SOURCE}}/.. && just build-supervisor
-    else
-        echo "Invalid BINARY specified. Must be either 'node' or 'supervisor'."
-        exit 1
     fi
 
     # Run the test with count=1 to avoid caching the test results.
